site_name: Proyecto Taller FHD
site_description: Documentación del proyecto PI de ASIR
site_author: Israel,Jose Carlos, Jesús
site_url: https://elimpermeable.github.io/Proyecto_Intermodular2ASIR_IJJ/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - 01 - Introducción: 01_Introduccion.md
  - 02 - Marco Tecnológico: 02_marco_tecnologico.md
  - 03 - Desarrollo: 03_Desarrollo.md
  - 04 - Resultados: 04_Resultados.md
  - 05 - Conclusiones y mejoras futuras: 05_Conclusiones y mejoras futuras.md
  - 06 - Bibliografia: 06_Bibliografia.md
  - 07 - Anexos: 07_Anexos.md
  

#  - Guía: guia.md