site_name: Proyecto Taller FHD
site_description: Documentación del proyecto PI de ASIR
site_author: Israel,Jose Carlos, Jesús
site_url: https://elimpermeable.github.io/Proyecto_Intermodular2ASIR_IJJ/

theme:
  name: material
  features:
    - layout.full_width
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Introducción: 01_Introduccion.md
  - Marco Tecnológico: 02_Marco_tecnologico.md
  - Planificación: 03_Planificacion.md
  - Desarrollo: 04_Desarrollo.md
  - Resultados: 05_Resultados.md
  - Conclusiones y mejoras futuras: 06_Conclusiones y mejoras futuras.md
  - Bibliografia: 07_Bibliografia.md
  - Anexos: 08_Anexos.md
  

#  - Guía: guia.md