site_name: Proyecto Taller FHD
site_description: Documentación del proyecto PI de ASIR
site_author: Israel,Jose Carlos, Jesús
site_url: https://elimpermeable.github.io/Proyecto_Intermodular2ASIR_IJJ/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - 01 - Introducción: 01_Introduccion.md
  - 02 - Marco Tecnológico: 02_Marco_tecnologico.md
  - 03 - Planificación: 03_Planificacion.md
  - 04 - Desarrollo: 04_Desarrollo.md
  - 05 - Resultados: 05_Resultados.md
  - 06 - Conclusiones y mejoras futuras: 06_Conclusiones y mejoras futuras.md
  - 07 - Bibliografia: 07_Bibliografia.md
  - 08 - Anexos: 08_Anexos.md
  

#  - Guía: guia.md